// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package usrdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                uuid.UUID
	Email             string
	AcquiredWatchTime int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Profile struct {
	ID             uuid.UUID
	Username       string
	Code           pgtype.Text
	ImagePath      pgtype.Text
	AgeRestriction pgtype.Int4
	SyncedThemeID  pgtype.Text
	AccountID      uuid.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ProfileRole struct {
	ID        uuid.UUID
	Name      string
	ProfileID uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ProhibitedMedium struct {
	ID        uuid.UUID
	ProfileID uuid.UUID
	MediaID   uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type WatchRecord struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	ProfileID uuid.NullUUID
	MediaID   uuid.UUID
	Duration  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
